// 한글 라벨 ↔ 영어 병기 (베트남 스태프 내부 미팅용)
export const EN = {
  // 손익 항목
  '요약': 'Summary',
  '매출': 'Revenue',
  '매출원가': 'Cost of Sales',
  '매출이익': 'Gross Profit',
  '판관비': 'SG&A',
  '영업이익': 'Operating Profit',
  '직접원가': 'Direct Cost',
  '영업이익률': 'OP Margin',
  '매출이익률': 'GP Margin',
  '원가율': 'COGS %',
  '판관비율': 'SG&A %',
  // 필터 카테고리
  '사업': 'Business',
  '지역': 'Region',
  '구분': 'Type',
  '세부': 'Detail',
  // 값
  '전체': 'All',
  'CL': 'CL',
  'FF': 'FF',
  '운송': 'Transport',
  '창고': 'Warehouse',
  '남부': 'South',
  '북부': 'North',
  '기타': 'Others',
  '해상': 'Sea',
  '항공': 'Air',
  'CC': 'Customs',
  'Haulage': 'Haulage',
  // 표/지표 보조
  '전년비': 'YoY',
  '합계': 'Total',
  '연간': 'Annual',
  '연도': 'Year',
  '항목': 'Item',
  '연간 비교': 'Annual',
  '월간 비교': 'Monthly',
  '당월': 'This Month',
  '누계': 'YTD',
  '계획比': 'vs Plan',
  '전월비': 'MoM',
  '달성률': 'Attain.',
  '실적': 'Actual',
  '계획': 'Plan',
  '전월': 'Prev M',
  '전년동월': 'LY',
  '당월 비교': 'This Month',
  '누계 비교': 'YTD',
  '연간 전망': 'Annual Outlook',
  '진행률': 'Progress',
  '연간 비교': 'Annual',
  '월간 비교': 'Monthly',
  '전년동월': 'YoY Mo.',
  '전월': 'Prev Mo.',
  '당월': 'Current',
  '전월비': 'MoM',
  '누계': 'YTD',
  '진행률': 'Progress',
  '연간 전망': 'Annual Fcst',
  '당월 비교': 'Current Month',
  '누계 비교': 'YTD',
  '실적': 'Actual',
  '계획': 'Plan',
  '연도별 비교': 'By Year',
  '월별 비교': 'By Month',
  '손익 비교 (연도별)': 'P&L by Year',
  // 내비게이션
  '경영계획': 'P&L Plan',
  '창고별': 'By Warehouse',
  '고객사별': 'By Customer',
  '계약': 'Contract',
  // 계약 탭/공통
  '계약 정보': 'Contract Info',
  '고객사': 'Customer',
  '벤더': 'Vendor',
  // 창고별/고객사별 섹션
  '월별 손익': 'Monthly P&L',
  '원가 항목 월별 모니터': 'Cost Monitor (Monthly)',
};

export const en = (k) => EN[k] || '';

// 계약 데이터 영문 필드 → 한국어 (시트 원본이 영문)
export const CONTRACT_KO = {
  'No.': '번호',
  // 창고 마스터
  'Warehouse ID': '창고 ID',
  'Warehouse Name': '창고명',
  'Location': '위치',
  'Map Location': '지도 위치',
  'Ownership Type': '소유 형태',
  'Warehouse Type': '창고 유형',
  'Price (VND/m²/month)': '단가 (VND/㎡/월)',
  'Extra cost': '추가 비용',
  'Extra Costs': '추가 비용',
  'Monthly Rental Fee (VND)': '월 임대료 (VND)',
  'Main Customer': '주요 고객',
  'Temperature Condition': '온도 조건',
  'Total Area (m²)': '총 면적 (㎡)',
  'Leasable Area (m²)': '임대가능 면적 (㎡)',
  'Operational Area (m²)': '운영 면적 (㎡)',
  'No. of Forklifts': '지게차 수',
  'No. of Workers': '작업자 수',
  'No. of Officer': '사무직 수',
  'Handling Volume (/month)': '처리 물량 (/월)',
  'Normal Handling Volume (/day)': '평균 처리 물량 (/일)',
  'Storage Volume (/month)': '보관 물량 (/월)',
  'Person in Charge': '담당자',
  'Current Vacancy Rate (%)': '현재 공실률 (%)',
  'Contract Period': '계약 기간',
  'Contract start': '계약 시작',
  'Contract start (DD/MM/YY)': '계약 시작 (일/월/년)',
  'Contract end': '계약 종료',
  'Rental Deposit': '임대 보증금',
  'Payment Term': '지급 조건',
  'Termination clause': '해지 조항',
  'Termination Clause': '해지 조항',
  'Vendor Liability Clause': '벤더 책임 조항',
  'Remarks': '비고',
  // 고객사 계약
  'Client': '고객사',
  'WH': '창고',
  'Contract type': '계약 유형',
  'Unit': '단위',
  'WH Monthy Bill (vnd)': '창고 월 청구액 (VND)',
  'Unloading': '하차',
  'Handling in (vnd)': '입고 작업비 (VND)',
  'Loading': '상차',
  'Handling out (vnd)': '출고 작업비 (VND)',
  'Storage Fee (vnd)': '보관료 (VND)',
  'TM Monthy Bill (vnd)': '운송 월 청구액 (VND)',
  'Pricing': '단가 정책',
  'TM Price': '운송 단가',
  'Inventoy Check': '재고 실사',
  'Working time': '작업 시간',
  'Cut off time': '마감 시간',
  'OT fee': '초과근무 수당',
  'Damaged goods Compensation': '파손품 보상',
  // 벤더
  'Vendor Name': '벤더명',
  'Operation Scppe': '운영 범위',
  'Details': '세부 내용',
  'WH Location': '창고 위치',
  'Customer name': '고객명',
  'Monthly Fee (vnd)': '월 비용 (VND)',
};

export const koField = (k) => CONTRACT_KO[k] || k;
